language: node_js
node_js:
  - node
script:
  - commitlint-travis
  - yarn build
deploy:
  provider: s3
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key: '$AWS_SECRET_ACCESS_KEY'
  bucket: richardharrah.com
  local-dir: dist
  acl: public_read
  skip_cleanup: true
  on:
    repo: Nunnery/richardharrah.com
    branch: master
env:
  global:
    - secure: FCyk+y5EdiXHMZBhPrNtC7AXSwx/+o/qMDqBRrTdDHzR1kYGnvz1gOlW0UObJ6o7TXGuQXHzYleSVtZfpJXfSVoWIVJvp4rs5mFA8ONKqbQAejGbg9FLTmKs+v/RaHMWKcba7pH7ov1NSdzkxKngSF1wohCpV7fZCGWrI9K4VZ409Ct+2poPioq/vwR+aDwSTrGkYdDEKPQ9o+gWYTU5HO8T2YeJ+SiBpHbYMP2sg+wWe/y4T5kNpMnlYJ4FFsTAhmuayX6+X0JWpbZ3D0MTb0Z2pOsWhkq9vjZlYo1PvGuv/oAM/LADmiH522Aof+eI5ie9pUl3S8dL+Ea8EgCHDOoBNNO1+waDcT9cLmc23jyOVJ/7Fz6esJoFVNemmiO+CjY9P89LF6FuEIZeWyCWdoj+fPxiapF+S5uIwSYseDPvZw4TPty0lhHE+Gl12njfpzKfxvx6cc0P2aAT5Qzi6RQoQ9X0djDqHRhU3sDMmFUkpc9aFrYO3gfSHPw1RL1cKsQFu60WiqnwaW5BzQiM/WasjPHafnnmF1k+5RQEou35NL4bjG29qoUg2W3BAvZJLwjHrhjPniOKFPqm3Dx2nDIV29Hc/AvcC2sxEx49BR++yJUu6iNe8EYsFxgJ7ggqD7qLabH+pWXgkIYga9MqEMxNyQLpXYc6z7Xib3Bc6kQ=
    - secure: crN3tBGv46QCeYy+h6WQdm3UMHfjUsEQiNrt+8EI251cYGCeG4M3uotXvkFwxsc4bM0+5Bec89dsfXwfWyFZ4zBcmjSIPGufJ5zvhHeCVgCqSVM1St1qPesedg7On9ZAEOR3+loRnnYYM+ipWsrSwRrfpBQiMkLG9merK/9Sc0OmifMhLO3mD8m1LPZwWdm0Q0Z0T/3ye9Ufq3STFf3IqhUTngq9T6WR6cO8A/6Pcm5//sNacMQ9andNdMB/lyAw8K0S06cY1Yl1VMX0Ssf0F6Dm3ME1njLYurp2YweFcOw7BB979MPbZHAX403yv86uJaiqYDubLTArvNwaEKsE4mv3nMJnfW2gAnMB0hhJ8rnhowGHkkNRww9w3K7VRL/K8fx8lWnfTAndoNcD8kSwo2k2gzClX5mZdf0KJnUp2n66jAKkhtLb4kY+rcjCL0zm4xnAtq6WZr1maM47FM0BG9waYNW0F6buSDFSFqUjXexJ7TdFsSAQJHwmtxoNkXy6kmjPpDjiqRizn2g6+iGaD0+oS6Fi4K6bB8G/a2eN0vP4HBm1LvAQ4JtjA3EDrlpIw69uC3SBnDhNNrGrZe5J6um6fkG+DZ2XT6ZEoH+BtD0qWAmXj6UMHyvY0/4uO0np7qKqTKRXnLJZNRgTtGiS2J95SM3SrS+R0gM6AVlhOzM=
